= Echo API project

This service responds to a http request with a simple "pong" message.

== Prerequisites

* JDK 8+

== Getting started

Create your project with:

[source]
----
git clone https://github.com/whitingjr/echo-api.git echo-api
----

== Running the project

Once you have retrieved the project, you can check that everything works with:

[source]
----
./gradlew test run
----

The command compiles the project, then  it launches the application, so you can check by yourself. Open your browser to http://localhost:8080/echo-api. You should see a pong message.

== Anatomy of the project

The project contains:

* the Gradle project and its configuration (`build.gradle`)
* a _main_ verticle file (src/main/java/org/jboss/echoapi/EchoService.java)

== Start to hack

1. Delete the `.git` directory
2. Open the `build.gradle` file and customize the `version`. You can also change the `mainVerticleName` variable to use your own package name and verticle class.
3. Run `./gradlew run`.

This last command relaunches Gradle and the application as soon as you change something in `src/main`.

== Building the project

To build the project, just use:

----
./gradlew shadowJar
----

It generates a _fat-jar_ in the `build/libs` directory.

